---

# doing this in a separate play for convenience, so the CONSUL_LOCK_SESSION_ID
# environment variable gets picked up on subsequent plays
- hosts: new_hashi_clients
  any_errors_fatal: true
  serial: 1
  remote_user: "{{ lookup('env','ANSIBLE_REMOTE_USER') }}"
  become: yes
  become_method: sudo
  vars:
    consul_bootstrap_token: "{{ lookup('env','CONSUL_BOOTSTRAP_TOKEN') }}"
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_bootstrap_token }}"
  tasks:
    - name: "creating lock sessions for Consul nodes"
      shell: "python3 /scripts/utilities/py_utilities/consul_kv.py create-lock-session"


- hosts: new_hashi_clients
  remote_user: "{{ lookup('env','ANSIBLE_REMOTE_USER') }}"
  serial: 1
  any_errors_fatal: true
  vars:
    consul_bootstrap_token: "{{ lookup('env','CONSUL_BOOTSTRAP_TOKEN') }}"
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_bootstrap_token }}"
  tasks:
    - name: "registering nodes on Consul KV data-store"
      shell: "source /etc/environment; python3 /scripts/utilities/py_utilities/consul_kv.py register-node"
      args:
        executable: /bin/bash
